### ISSUE TITLE
Feature request: Canned cabbage / sauerkraut

### ISSUE THREAD

**Issue by Montandalar** [h-v-smacker/canned_food#3]
With the newly-added cabbages in farming_redo by Felfa, it would be good to add a way to can cabbage and allow it to age into sauerkraut.

**Comment by Bastrabun** [comment]
For those interested I forked and solved this in https://gitea.your-land.de/your-land/canned_food/commit/82a53f04f84b26c6d4b762c1e303b925a250edfd

**Comment by Montandalar** [comment]
Ok so it turns out sauerkraut is  made with the `wine` mod: https://gitlab.com/Felfa/wine. Also, cabbage is not normally canned in real life except as sauerkraut. Thoughts?

**Comment by h-v-smacker** [comment]
There are dozens kinds of wood that are different but in texture's hue, usually at least two kinds of blueberries that are literally meant to be the same thing, and a whole array of tools made from different materials. I don't see how having two different sauerkraut varieties is a reason for concern.

**Comment by Montandalar** [comment]
Not an issue then
