### ISSUE TITLE
Blueberry jam recipes are reversed

### ISSUE THREAD

**Issue by hlqkj** [h-v-smacker/canned_food#5]
The wild/normal blueberry jam and blueberry kind are mixed:

- Normal blueberries (`default:blueberries` -- [here](https://github.com/minetest/minetest_game/blob/92701885d086e5123c2c8cca0774e9d9e2327558/mods/default/craftitems.lua#L208-L213)) are needed to craft a "Wild blueberry jam": https://github.com/h-v-smacker/canned_food/blob/755526d66b804c8653880b376f66dec0bda787d1/init.lua#L41-L48
- Wild blueberries (`farming:blueberries` -- see [here](https://notabug.org/TenPlus1/farming/src/2e2cd77184da2a15e0f03b426bbd46421bc234c9/crops/blueberry.lua#L5-L14)) are needed to craft a "Blueberry jam": https://github.com/h-v-smacker/canned_food/blob/755526d66b804c8653880b376f66dec0bda787d1/init.lua#L107-L114

Not such important but worth fixing, since I've had a few players noting this.

EDIT: added link.

**Comment by h-v-smacker** [comment]
I don't think I understand your issue here. There are two kinds of jam. One is made with berries from cubic bushes. The other with berries from small plants growing on farming soil. They produce different items, hence different jams.

**Comment by hlqkj** [comment]
The issue is the 2 recipes are reversed. The normal jam requires "**wild**" berries, and the wild jam recipe requires "**normal**" berries.
Sorry if my first comment wasn't so clear, I'm not english...

**Comment by h-v-smacker** [comment]
Well... my logic is as follows: the square bushes are more fitting the description of "wild" berries: large bushes, no special soil or water needed. Meanwhile, the small bush blueberries need farming soil to grow, so they are more like "domestic" or "garden" variety (except when you find them in the wild, but then again, most people use those found berries as seeds).

**Comment by hlqkj** [comment]
I am reporting this here only because I've got some players reporting it to me. Your logic makes sense actually, but what I see is confusing for the players is the items displayed names.

I'm posting two screenshots to show what I mean, then I'll drop this discussion, so feel free to close it if it doesn't make sense to you (the text over the craft grid is from the mouse tool-tip which appears on hovering).

![Screenshot 2021-08-04 110048](https://user-images.githubusercontent.com/63740606/128154980-e2961646-edcd-4c3d-83f3-eb86ce89c843.jpg)
![Screenshot 2021-08-04 110125](https://user-images.githubusercontent.com/63740606/128154990-badca056-71e3-4e31-8cc3-d2e62418314f.jpg)

**Comment by h-v-smacker** [comment]
Aha, now I see — you see, I largely ignore the proper item names, since I'm not a new player and have no reason to explore the game. I gotta think on this though, since my initial logic (see above) was connected to the way the berries are obtained, not their names.

**Comment by hlqkj** [comment]
I see your point too and it makes great sense: I didn't think at that at first. Have to admit, the confusion actually originates in the `farming` mod where they termed a cultivated crop as 'wild'. That choice may have been made just to distinguish them from the `default` ones — which are the *real* wild ones.

We may try to point out the issue in the `farming` repo instead? The reason could be that the 'wild' adjective doesn't make sense since they can be farmed.

EDIT: actually, just renaming `farming:blueberries` would not completely solve this: we would still be having the "Wild bueberry jam" made with "Blueberries" from the default mod, which 99% will not change I'm afraid...

**Comment by h-v-smacker** [comment]
I think petitioning tenplus1 to rename blueberries from "wild" into "garden" or something would do nicely. As for the remaining part of the scheme, I don't think that it would cause as much confusion when we have "wild bb jam" made from "blueberries" and "bb jam" made from "garden blueberries". Well, it would be nice to have the default blueberries renamed into wild bbs, but I think reaching farming mod's dev is far easier.

**Comment by hlqkj** [comment]
Closing because I doubt that neither minetest_game and farming will consider such a change, in reality they should both find a coherent convention and apply it. In any case I'd like to thank you for considering this issue at first :)

**Comment by h-v-smacker** [comment]
I dunno about that. Let's see what TenPlus1 would think about it:
https://notabug.org/TenPlus1/farming/issues/58

**Comment by tenplus1** [comment]
In the jam recipe why not use the {food_blueberries=1} group instead of an actual item, that way both kinds of blueberries can be used for the same recipe. e.g. https://notabug.org/TenPlus1/farming/src/master/crops/blueberry.lua#L23

**Comment by hlqkj** [comment]
That could be a solution but would force @h-v-smacker waiving his idea of having two jams. Even in that case, though, the oddity would remain: a wild specie is by definition something that can't be grown artificially, or which is so difficult to grow that it's *de facto* considered not cultivable.

The ideal would be having `farming:blueberries` called 'Blueberries' and having `default:blueberries` called 'Wild blueberries' instead (even the inventory images would match better, since wild blueberries are smaller and more dense than cultivated one -- see on the internet) but sadly `minetest_game` development seem to be frozen now...

**Comment by h-v-smacker** [comment]
Well, the idea of having two jams is also connected to how the jams are represented: each jar has a sticker on it with the little image of the canned product, and the color for the contents of the jar is also borrowed from that image. A group recipe would make a universal jam (and instead of wild/garden we can have unsweetened/with sugar), but that also means something is to be done with the sticker, or else players can be similarly confused: why a jam made from farmed berries has an image of different berries on it, and vice versa.
